name: Create-OpenMapTiles
on:
  workflow_dispatch:
    inputs:
      file_URL:
        description: 'input http://download.openstreetmap.fr/extracts/asia/china/anhui.osm.pbf osm file URL'
        required: true
        default: 'http://download.openstreetmap.fr/extracts/asia/china/anhui.osm.pbf'  
env:
  TZ: Asia/Shanghai

jobs:
  Create-OpenMapTiles:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: Initialization running environment
        run: |
          sudo ln -sf /bin/bash /bin/sh 
          sudo mkdir -p /UpReleaseArtifact && sudo -E chmod 777 /UpReleaseArtifact
          chmod +x ./extern-disk-space.sh
          # ./extern-disk-space.sh
      - name: Download map file 
        run: |
          sudo apt install build-essential libboost-dev libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev libboost-system-dev liblua5.1-0-dev libprotobuf-dev libshp-dev libsqlite3-dev protobuf-compiler rapidjson-dev
          git clone https://github.com/systemed/tilemaker -b master
          cd tilemaker
          make
          sudo make install
          df -h
          
          curl -o custom.osm.pbf '${{ github.event.inputs.file_URL }}'
          sudo mkdir -p ./coastline && sudo -E chmod 777 ./coastline
          sudo mkdir -p ./TilesOut && sudo -E chmod 777 ./TilesOut
          wget  https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip
          unzip -l -o water-polygons-split-4326.zip -d ./coastline 
          cd ./coastline
          ls -al
          cd ../
          tilemaker --input custom.osm.pbf  --output TilesOut/ --config ../config-openmaptiles.json --process ../process-openmaptiles.lua --verbose
          
           
      - name: zip Tiles file
        run: |
          cd tilemaker
          tar  cvzf - TilesOut/ | split -b 2040m - tiles-mbtiles.tar.gz.
          mv tiles-mbtiles.tar.gz.* /UpReleaseArtifact
          ls -al /UpReleaseArtifact
          
      - name: clear src release    #v1.0.0 is src
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: v1.0.0   #v1.0.0 is src
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: release src    #v1.0.0 is src
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/UpReleaseArtifact/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag:  "v1.0.0"    #v1.0.0 is src
